# Generated by Django 3.2.5 on 2021-07-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_bookmodel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='cover',
            field=models.ImageField(upload_to='images', verbose_name='cover'),
        ),
    ]
